################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C67_SRCS := 
S_UPPER_SRCS := 
CMD_UPPER_SRCS := 
LIB_SRCS := 
OBJ_SRCS := 
C55_SRCS := 
C_SRCS := 
A_SRCS := 
CPP_SRCS := 
LD_SRCS := 
O_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
ASM_UPPER_SRCS := 
OPT_SRCS := 
C43_SRCS := 
C64_SRCS := 
CMD_SRCS := 
S55_SRCS := 
S62_SRCS := 
S67_SRCS := 
C++_SRCS := 
SA_SRCS := 
S64_SRCS := 
C_UPPER_SRCS := 
S??_SRCS := 
S43_SRCS := 
C62_SRCS := 
C??_SRCS := 
CC_SRCS := 
S62_DEPS := 
ASM_DEPS := 
C55_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 
C64_DEPS := 
C43_DEPS := 
C62_DEPS := 
OBJS := 
C??_DEPS := 
S??_DEPS := 
S55_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
SA_DEPS := 
TMS470_LIBRARY_OUTPUTS := 
C++_DEPS := 
CC_DEPS := 
S64_DEPS := 
CXX_DEPS := 
S43_DEPS := 
S67_DEPS := 
C67_DEPS := 
ASM_UPPER_DEPS := 
OPT_DEPS := 
CPP_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C67_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S64_DEPS__QUOTED := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
TMS470_LIBRARY_OUTPUTS__QUOTED := 
S62_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
OBJS__QUOTED := 
S??_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
C64_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Messaging/MessageQueue \
Messaging/Message \
Messaging/MemoryManager \
Lib \
API \

