#ifndef LEDCONSTANTS_H_
#define LEDCONSTANTS_H_

enum LED {
    LED1 = 0,
    LED2 = 1
};


enum LEDServiceCommand {
    SERVICE_TOGGLE_LED,
    SERVICE_SWITCH_LED_ON,
    SERVICE_SWITCH_LED_OFF,
    SERVICE_GET_LED_STATUS
};

#endif /*LEDCONSTANTS_H_*/
